djeet/urls.py
from django.urls import path
from django.views.generic.base import TemplateView

from .views import FeedView


app_name = "djeet"

urlpatterns = [
    path("feed/", FeedView.as_view(), name="feed"),
]

djeeterprofile/urls.py
from django.urls import path, include
from django.conf.urls import handler404


from .views import (
    ProfileView, FrontPageView, SignoutView, FollowsView, FollowersView,
    FollowView, StopFollowView, LikeView, StopLikeView, LikesView,
)


app_name = "djeeterprofile"

urlpatterns = [
    path("", FrontPageView.as_view(), name="frontpage"),
    path("signout/", SignoutView.as_view(), name="signout"),
    path("<str:username>/follows/", FollowsView.as_view(), name="follows"),
    path("<str:username>/following/", FollowersView.as_view(), name="following"),
    path("<str:username>/follow/", FollowView.as_view(), name="follow"),
    path("<str:username>/stopfollow/", StopFollowView.as_view(), name="stopfollow"),
    path("like/<str:djeet_id>/", LikeView.as_view(), name="like"),
    path("stoplike/<str:djeet_id>/", StopLikeView.as_view(), name="stoplike"),
    path("<str:username>/likes/", LikesView.as_view(), name="likes"),
    path("<str:username>/", ProfileView.as_view(), name="profile"),
]

handler404 = 'djeeterprofile.views.page_not_found'

djitter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("djeet.urls", namespace="djeet")),
    path("", include("djeeterprofile.urls", namespace="profile")),
]

djeeterprofile/models.py
from django.db import models
from users.models import User
from djeet.models import Djeet


class DjeeterProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.DO_NOTHING)
    follows = models.ManyToManyField('self', related_name='followed_by', symmetrical=False)
    likes = models.ManyToManyField(Djeet, related_name="liked_by", symmetrical=False)

User.djeeterprofile = property(lambda u: DjeeterProfile.objects.get_or_create(user=u)[0])

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _
from django.core import validators


class User(AbstractUser):
    nickname = models.CharField(max_length=10, default="unknown")
    username = models.CharField(_('username'), max_length=10, unique=True,
        help_text=_('Required. 10 characters or fewer. Letters, digits and '
                    '_ only.'),
        validators=[
            validators.RegexValidator(r'^[\w]+$',
                                      _('Enter a valid username. '
                                        'This value may contain only letters, numbers '
                                        'and _ characters.'), 'invalid'),
        ],
        error_messages={
            'unique': _("A user with that username already exists."),
        })
    profile = models.CharField(max_length=140, default="")

djeeterprofile/forms.py
from django.contrib.auth.forms import (
    AuthenticationForm, UserCreationForm,
)
from users.models import User
from django import forms
from django.utils.html import strip_tags

class SignupForm(UserCreationForm):
    email = forms.EmailField(
        required=True,
        widget=forms.widgets.TextInput(attrs={
            'placeholder': 'Email',
            'class': 'form-control'}))
    username = forms.CharField(
        widget=forms.widgets.TextInput(attrs={
            'placeholder': 'Username',
            'class': 'form-control'}))

    nickname = forms.CharField(
        widget=forms.widgets.TextInput(attrs={
            'placeholder': 'Nickname',
            'class': 'form-control'}))

    password1 = forms.CharField(
        widget=forms.widgets.PasswordInput(attrs={
            'placeholder': 'Password',
            'class': 'form-control'}))
    password2 = forms.CharField(
        widget=forms.widgets.PasswordInput(attrs={
            'placeholder': 'Password Confirmation',
            'class': 'form-control'}))

    class Meta:
        fields = ['email', 'username', 'nickname',
                  'password1', 'password2']
        model = User


class SigninForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.widgets.TextInput(attrs={
            'placeholder': 'Username',
            'class': 'form-control'}))
    password = forms.CharField(
        widget=forms.widgets.PasswordInput(attrs={
            'placeholder': 'Password',
            'class': 'form-control'}))

djeeterprofile/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LogoutView

from djeeterprofile.forms import SignupForm, SigninForm
from djeet.forms import DjeetForm
from users.models import User
from djeet.models import Djeet


def top_url():
    return reverse("profile:frontpage")

def return_to_top():
    topurl = top_url()
    return redirect(topurl)


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = "djeeterprofile/profile.html"

    def get(self, request, username):
        context = {
            "user": get_object_or_404(User, username=username),
            "form": DjeetForm()
        }
        return self.render_to_response(context)

    def post(self, request, username):
        user = get_object_or_404(User, username=username)
        form = DjeetForm(data=request.POST)

        if form.is_valid():
            djeet = form.save(commit=False)
            djeet.user = user
            djeet.save()

        return self.render_to_response({ "form": form, "user": user, })


class FrontPageView(TemplateView):
    template_name = "djitter/frontpage.html"

    def get(self, request):
        if request.user.is_authenticated:
            return redirect(reverse("profile:profile", args=[request.user.username]))
        
        signupform = SignupForm()
        signinform = SigninForm()

        context = {
            "signupform": signupform,
            "signinform": signinform
        }
        return self.render_to_response(context)

    def post(self, request):
        if 'signupform' in request.POST:
            signupform = SignupForm(data=request.POST)
            signinform = SigninForm()
    
            if signupform.is_valid():
                username = signupform.cleaned_data['username']
                password = signupform.cleaned_data['password1']
                signupform.save()
                user = authenticate(username=username, password=password)
                login(request, user)
                return return_to_top()
   
        else:
            signinform = SigninForm(data=request.POST)
            signupform = SignupForm()
   
            if signinform.is_valid():
                login(request, signinform.get_user())
                return return_to_top()

        context = {
            "signupform": signupform,
            "signinform": signinform
        }
        return self.render_to_response(context)


class SignoutView(LogoutView):
    next_page = "/"


class FollowsView(TemplateView):
    template_name = "djeeterprofile/users.html"

    def get(self, request, username):
        user = User.objects.get(username=username)
        djeeterprofiles = user.djeeterprofile.follows.select_related("user").all()
        return self.render_to_response({
            "title": "Follows",
            "djeeterprofiles": djeeterprofiles,
        })


class FollowersView(TemplateView):
    template_name = "djeeterprofile/users.html"

    def get(self, request, username):
        user = User.objects.get(username=username)
        djeeterprofiles = user.djeeterprofile.followed_by.select_related("user").all()
        return self.render_to_response({
            "title": "Followers",
            "djeeterprofiles": djeeterprofiles,
        })

    
class FollowView(LoginRequiredMixin, TemplateView):
    
    def get(self, request, username):
        user = get_object_or_404(User, username=username)
        request.user.djeeterprofile.follows.add(user.djeeterprofile)
        return HttpResponseRedirect(reverse("profile:profile", kwargs={"username": username}))


class StopFollowView(LoginRequiredMixin, TemplateView):
    
    def get(self, request, username):
        user = get_object_or_404(User, username=username)
        request.user.djeeterprofile.follows.remove(user.djeeterprofile)
        return HttpResponseRedirect(reverse("profile:profile", kwargs={"username": username}))


class LikeView(LoginRequiredMixin, TemplateView):
    
    def get(self, request, djeet_id):
        djeet = get_object_or_404(Djeet, id=djeet_id)
        request.user.djeeterprofile.likes.add(djeet)
        return redirect(request.META["HTTP_REFERER"])


class StopLikeView(LoginRequiredMixin, TemplateView):
    
    def get(self, request, djeet_id):
        djeet = get_object_or_404(Djeet, id=djeet_id)
        request.user.djeeterprofile.likes.remove(djeet)
        return redirect(request.META["HTTP_REFERER"])


class LikesView(TemplateView):
    template_name = "djeet/djeets.html"

    def get(self, request, username):
        user = get_object_or_404(User, username=username)
        djeets = user.djeeterprofile.likes.select_related("user").all()
        return self.render_to_response({
            "title": "Likes",
            "djeets": djeets,
        })


def page_not_found(request, template_name="404.html"):
    return render(request, template_name, {})

users/views.py
from django.shortcuts import render

# Create your views here.

djeeterprofile/templates/djeeterprofile/_profile.html
{% load static %}

  <div class="profile">
    <div class="card profile__inner" style="">
      <figure class="profile__icon">
        <img class="card-img-top profile__img" src="{% static "djeeterprofile/img/icon.png" %}">
      </figure>
      <div class="card-body">
        <div class="profile__user">
          <div class="profile__user-name">
            <h5 class="card-title">{{ user.nickname }}</h3>
            <p class="card-subtitle text-muted">@{{ user.username }}</p>
            <p class="card-text">{{ user.profile }}</p>
          </div>
        </div>
        <div class="profile__follow">
          {% ifnotequal request.user user %}
            {% if request.user.djeeterprofile in user.djeeterprofile.followed_by.all %}
              <a href="{% url "profile:stopfollow" user.username %}" class="btn btn-danger">Unfollow</a>
            {% else %}
              <a href="{% url "profile:follow" user.username %}" class="btn btn-success">Follow</a>
            {% endif %}
          {% endifnotequal %}
        </div>

        <hr>
        <ul class="profile__links">
          <li class="profile__link">
            <a class="profile__link-inner">
              <p class="profile__link-title">Djeets</p>
              <p class="profile__link-number">{{ user.djeets.all.count }}</p> 
            </a>
          </li>
          <li class="profile__link">
            <a class="profile__link-inner" href="{% url "profile:likes" user.username %}">
              <p class="profile__link-title">Likes</p>
              <p class="profile__link-number">{{ user.djeeterprofile.likes.count }}</p>
            </a>
          </li>
          <li class="profile__link">
            <a class="profile__link-inner" href="{% url "profile:follows" user.username %}">
              <p class="profile__link-title">Follows</p>
              <p class="profile__link-number">{{ user.djeeterprofile.follows.count }}</p> 
            </a>
          </li>
          <li class="profile__link">
            <a class="profile__link-inner" href="{% url "profile:following" user.username %}">
              <p class="profile__link-title">Followers</p>
              <p class="profile__link-number">{{ user.djeeterprofile.followed_by.count }}</p> 
            </a>
          </li>
        </ul>
        <hr>
        {% if form.errors %}
          {% for field in form %}
            {% for error in form.errors %}
              <div class="alert alert-danger">
                <b>{{ error|escape }}</b>
              </div>
            {% endfor %}
          {% endfor %}
          {% for error in form.non_field_errors %}
             <div class="alert alert-danger">
               <b>{{ error|escape }}</b>
             </div>
          {% endfor %}
        {% endif %}
        <form action="{% url "profile:profile" request.user.username %}" method="post">
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group">
              {{ field }}
            </div>
          {% endfor %}

          <input type="hidden" value="{{ request.path }}" name="redirect">
          <input type="submit" value="Post djeet" class="btn btn-primary">
        </form>
 
      </div>
    </div>
  </div>

djeeterprofile/templates/djeeterprofile/_profile_simple.html
{% load static %}

  <div class="profile">
    <div class="card profile__inner" style="">
      <figure class="profile__icon">
        <img class="card-img-top profile__img" src="{% static "djeeterprofile/img/icon.png" %}">
      </figure>
      <div class="card-body">
        <div class="profile__user">
          <div class="profile__user-name">
            <h5 class="card-title">{{ user.nickname }}</h3>
            <p class="card-subtitle text-muted">@{{ user.username }}</p>
            <p class="card-text">{{ user.profile }}</p>
          </div>
        </div>
        <div class="profile__follow">
          {% ifnotequal request.user user %}
            {% if request.user.djeeterprofile in user.djeeterprofile.followed_by.all %}
              <a href="{% url "profile:stopfollow" user.username %}" class="btn btn-danger">Unfollow</a>
            {% else %}
              <a href="{% url "profile:follow" user.username %}" class="btn btn-success">Follow</a>
            {% endif %}
          {% endifnotequal %}
        </div>

      </div>
    </div>
  </div>

djeeterprofile/templates/djeeterprofile/profile.html
{% extends 'djitter/base.html' %}
{% load static %}

{% block main %}
<div class="main">
  <!-- Sidebar -->
  {% include "djeeterprofile/_profile.html" %}

  <!-- Feed -->
  <div class="timeline">

    {% if user.djeets.all %}
      {% for djeet in user.djeets.all %}
        {% include "djeet/_djeet.html" %}
      {% endfor %}
    {% else %}
      <p>No djeets yet!</p>
    {% endif %}
  </div>

</div>
{% endblock %}

djeeterprofile/templates/djeeterprofile/users.html
{% extends 'djitter/base.html' %}

{% block main %}
<div>
  <h1>{{ title }}</h1>
  <ul class="users">
    {% for djeeter in djeeterprofiles %}
      <li>{% include "djeeterprofile/_profile_simple.html" with user=djeeter.user %}</li>
    {% endfor %}
  </ul>
{% endblock %}