djeet/urls.py
from django.urls import path
from django.views.generic.base import TemplateView

from .views import FeedView


app_name = "djeet"

urlpatterns = [
    path("feed/", FeedView.as_view(), name="feed"),
]

djeeterprofile/urls.py
from django.urls import path, include
from django.conf.urls import handler404


from .views import (
    ProfileView, FrontPageView, SignoutView, FollowsView, FollowersView,
    FollowView, StopFollowView, LikeView, StopLikeView, LikesView,
)


app_name = "djeeterprofile"

urlpatterns = [
    path("", FrontPageView.as_view(), name="frontpage"),
    path("signout/", SignoutView.as_view(), name="signout"),
    path("<str:username>/follows/", FollowsView.as_view(), name="follows"),
    path("<str:username>/following/", FollowersView.as_view(), name="following"),
    path("<str:username>/follow/", FollowView.as_view(), name="follow"),
    path("<str:username>/stopfollow/", StopFollowView.as_view(), name="stopfollow"),
    path("like/<str:djeet_id>/", LikeView.as_view(), name="like"),
    path("stoplike/<str:djeet_id>/", StopLikeView.as_view(), name="stoplike"),
    path("<str:username>/likes/", LikesView.as_view(), name="likes"),
    path("<str:username>/", ProfileView.as_view(), name="profile"),
]

handler404 = 'djeeterprofile.views.page_not_found'

djitter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("djeet.urls", namespace="djeet")),
    path("", include("djeeterprofile.urls", namespace="profile")),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _
from django.core import validators


class User(AbstractUser):
    nickname = models.CharField(max_length=10, default="unknown")
    username = models.CharField(_('username'), max_length=10, unique=True,
        help_text=_('Required. 10 characters or fewer. Letters, digits and '
                    '_ only.'),
        validators=[
            validators.RegexValidator(r'^[\w]+$',
                                      _('Enter a valid username. '
                                        'This value may contain only letters, numbers '
                                        'and _ characters.'), 'invalid'),
        ],
        error_messages={
            'unique': _("A user with that username already exists."),
        })
    profile = models.CharField(max_length=140, default="")

djitter/views.py
from django.shortcuts import render

users/views.py
from django.shortcuts import render

# Create your views here.

djitter/templates/djitter/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Djitter</title>

    <link rel="stylesheet" href="{% static "djeeterprofile/css/cssreset-min.css" %}">    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "djeeterprofile/css/layout.css" %}">
  </head>

  <body style="padding-top: 80px;">
    <!-- Navbar -->
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top topbar">
      <a class="navbar-brand" href="{% url "profile:frontpage" %}">Djitter</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url "profile:frontpage" %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "djeet:feed" %}">Feed</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "profile:likes" username=request.user.username %}">Likes</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "profile:signout" %}">Sign out</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <!-- End Navbar -->

    <!-- Main -->
    <main role="main" class="container">
      {% block main %}
      {% endblock %}
    </main>
    <!-- End Main -->

    <!-- Scripts - Bootstrap -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

djitter/templates/djitter/frontpage.html
{% extends 'djitter/base.html' %} {% block main %} <div class="row">
  <div class="col-12">
    <h1>Welcome to Djitter</h1>
  </div>
</div>

<hr>

<div class="row">

  <div class="col-6">
    <h2>Sign in</h2>

    {% if signinform.errors %}
      {% for field in signinform %}
        {% for error in field.errors %}
          <div class="alert alert-danger">
            <b>{{ error|escape }}</b>
          </div>
        {% endfor %}
      {% endfor %}
      {% for error in signinform.non_field_errors %}
        <div class="alert alert-danger">
          <b>{{ error|escape }}</b>
        </div>
      {% endfor %}
    {% endif %}

    <form action="." method="post">
      {% csrf_token %}

      {% for field in signinform %}
        <div class="form-group">
          {{ field }}
        </div>
      {% endfor %}

      <input type="submit" value="Sign in" name="signinform" class="btn btn-primary">
    </form>
  </div>

  <div class="col-6">
    <h3>Don't have an account yet?</h3>

    {% if signupform.non_field_errors %}
      <div class="alert danger">
        {{ signupform.non_field_errors }}
      </div>
    {% endif %}

    {% if signupform.errors %}
      {% for field in signupform %}
        {% for error in field.errors %}
          <div class="alert alert-danger">
            <b>{{ error|escape }}</b>
          </div>
        {% endfor %}
      {% endfor %}
      {% for error in signupform.non_field_errors %}
        <div class="alert alert-danger">
          <b>{{ error|escape }}</b>
        </div>
      {% endfor %}
    {% endif %}

    <form action="." method="post">
      {% csrf_token %}

      {% for field in signupform %}
        <div class="form-group">
          {{ field }}
        </div>
      {% endfor %}

      <input type="submit" value="Sign up" name="signupform" class="btn btn-primary">
    </form>
  </div>
</div>
{% endblock %}

djitter/templates/djitter/users.html
{% extends 'base.html' %}

{% block main %}
<div>
  <h1>{{ title }}</h1>
  <ul>
    {% for djeeter in djeeterprofiles %}
      <li><a href="/{{ djeeter.user.username }}/">@{{ djeeter.user.username }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}