djeet/urls.py
from django.urls import path
from django.views.generic.base import TemplateView

from .views import FeedView


app_name = "djeet"

urlpatterns = [
    path("feed/", FeedView.as_view(), name="feed"),
]

djeeterprofile/urls.py
from django.urls import path, include
from django.conf.urls import handler404


from .views import (
    ProfileView, FrontPageView, SignoutView, FollowsView, FollowersView,
    FollowView, StopFollowView, LikeView, StopLikeView, LikesView,
)


app_name = "djeeterprofile"

urlpatterns = [
    path("", FrontPageView.as_view(), name="frontpage"),
    path("signout/", SignoutView.as_view(), name="signout"),
    path("<str:username>/follows/", FollowsView.as_view(), name="follows"),
    path("<str:username>/following/", FollowersView.as_view(), name="following"),
    path("<str:username>/follow/", FollowView.as_view(), name="follow"),
    path("<str:username>/stopfollow/", StopFollowView.as_view(), name="stopfollow"),
    path("like/<str:djeet_id>/", LikeView.as_view(), name="like"),
    path("stoplike/<str:djeet_id>/", StopLikeView.as_view(), name="stoplike"),
    path("<str:username>/likes/", LikesView.as_view(), name="likes"),
    path("<str:username>/", ProfileView.as_view(), name="profile"),
]

handler404 = 'djeeterprofile.views.page_not_found'

djitter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("djeet.urls", namespace="djeet")),
    path("", include("djeeterprofile.urls", namespace="profile")),
]

djeet/models.py
from django.db import models
from users.models import User

class Djeet(models.Model):
  user = models.ForeignKey(User, related_name='djeets', on_delete=models.DO_NOTHING)
  body = models.CharField(max_length=140)
  created_at = models.DateTimeField(auto_now_add=True)

  class Meta:
    ordering = ('-created_at',)

djeet/forms.py
from django import forms
from django.utils.html import strip_tags

from .models import Djeet


class DjeetForm(forms.ModelForm):
    body = forms.CharField(
        required=True,
        widget=forms.widgets.Textarea(attrs={
            "placeholder": "Djeet",
            "class": "form-control",
            "rows": 5,
            "style": "resize: none;"}))

    class Meta:
        model = Djeet
        exclude = ("user", )

djeet/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView

from .models import Djeet


class FeedView(TemplateView):
    template_name = "djeet/djeets.html"

    def get(self, request):
        userids = [item.id for item in request.user.djeeterprofile.follows.all()]
        userids.append(request.user.id)
        djeets = list(Djeet.objects.filter(user_id__in=userids)[:25])
        return self.render_to_response({
            "title": "Feed",
            "djeets": djeets
        })

djeet/templates/djeet/_djeet.html
{% load static %}

<div class="card djeet" style="margin-bottom: 20px;">
  <div class="card-body">
    <div class="djeet__user">
      <figure class="djeet__usericon">
        <img class="djeet__img" src="{% static "djeeterprofile/img/icon.png" %}">
      </figure>
      <div class="djeet__username">
        <a class="text-black" href="{% url "profile:profile" username=djeet.user.username %}"><p class="card-text mb-0"><b>{{ djeet.user.nickname }}</b></p></a>
        <p class="card-text text-muted">@{{ djeet.user.username }}</p>
      </div>
    </div>
    <p class="card-text">{{ djeet.body }}</p>
    <p class="card-text"><small class="text-muted">{{ djeet.created_at }}</small></p>
    <div class="djeet__action">
      {% if not request.user.djeeterprofile in djeet.liked_by.all %}
        <a class="btn btn-success btn-like" href="{% url "profile:like" djeet_id=djeet.id %}">Like</a>
      {% else %}
        <a class="btn btn-danger btn-like" href="{% url "profile:stoplike" djeet_id=djeet.id %}">Stop Like</a>
      {% endif %}

    </div>
  </div>
</div>

djeet/templates/djeet/djeets.html
{% extends 'djitter/base.html' %}

{% block main %}
<div class="row">
  <div class="col-12">
    <h3>{{ title }}</h3>

    {% for djeet in djeets %}
      {% include "djeet/_djeet.html" %}
    {% endfor %}
  </div>
</div>
{% endblock %}

djeet/templates/djeet/feed.html
{% extends 'djitter/base.html' %}

{% block main %}
<div class="row">
  <div class="col-12">
    <h3>Feed</h3>

    {% for djeet in djeets %}
      {% include "djeet/_djeet.html" %}
    {% endfor %}
  </div>
</div>
{% endblock %}